// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: sound_data_streaming.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SoundServiceClient is the client API for SoundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoundServiceClient interface {
	GetSoundJustHello(ctx context.Context, opts ...grpc.CallOption) (SoundService_GetSoundJustHelloClient, error)
	GetSound(ctx context.Context, opts ...grpc.CallOption) (SoundService_GetSoundClient, error)
}

type soundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoundServiceClient(cc grpc.ClientConnInterface) SoundServiceClient {
	return &soundServiceClient{cc}
}

func (c *soundServiceClient) GetSoundJustHello(ctx context.Context, opts ...grpc.CallOption) (SoundService_GetSoundJustHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &SoundService_ServiceDesc.Streams[0], "/proto.SoundService/GetSoundJustHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &soundServiceGetSoundJustHelloClient{stream}
	return x, nil
}

type SoundService_GetSoundJustHelloClient interface {
	Send(*ChatClientMessage) error
	Recv() (*ChatServerMessage, error)
	grpc.ClientStream
}

type soundServiceGetSoundJustHelloClient struct {
	grpc.ClientStream
}

func (x *soundServiceGetSoundJustHelloClient) Send(m *ChatClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *soundServiceGetSoundJustHelloClient) Recv() (*ChatServerMessage, error) {
	m := new(ChatServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *soundServiceClient) GetSound(ctx context.Context, opts ...grpc.CallOption) (SoundService_GetSoundClient, error) {
	stream, err := c.cc.NewStream(ctx, &SoundService_ServiceDesc.Streams[1], "/proto.SoundService/GetSound", opts...)
	if err != nil {
		return nil, err
	}
	x := &soundServiceGetSoundClient{stream}
	return x, nil
}

type SoundService_GetSoundClient interface {
	Send(*ChatClientMessage) error
	Recv() (*ChatServerMessage, error)
	grpc.ClientStream
}

type soundServiceGetSoundClient struct {
	grpc.ClientStream
}

func (x *soundServiceGetSoundClient) Send(m *ChatClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *soundServiceGetSoundClient) Recv() (*ChatServerMessage, error) {
	m := new(ChatServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SoundServiceServer is the server API for SoundService service.
// All implementations must embed UnimplementedSoundServiceServer
// for forward compatibility
type SoundServiceServer interface {
	GetSoundJustHello(SoundService_GetSoundJustHelloServer) error
	GetSound(SoundService_GetSoundServer) error
	mustEmbedUnimplementedSoundServiceServer()
}

// UnimplementedSoundServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSoundServiceServer struct {
}

func (UnimplementedSoundServiceServer) GetSoundJustHello(SoundService_GetSoundJustHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSoundJustHello not implemented")
}
func (UnimplementedSoundServiceServer) GetSound(SoundService_GetSoundServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSound not implemented")
}
func (UnimplementedSoundServiceServer) mustEmbedUnimplementedSoundServiceServer() {}

// UnsafeSoundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoundServiceServer will
// result in compilation errors.
type UnsafeSoundServiceServer interface {
	mustEmbedUnimplementedSoundServiceServer()
}

func RegisterSoundServiceServer(s grpc.ServiceRegistrar, srv SoundServiceServer) {
	s.RegisterService(&SoundService_ServiceDesc, srv)
}

func _SoundService_GetSoundJustHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SoundServiceServer).GetSoundJustHello(&soundServiceGetSoundJustHelloServer{stream})
}

type SoundService_GetSoundJustHelloServer interface {
	Send(*ChatServerMessage) error
	Recv() (*ChatClientMessage, error)
	grpc.ServerStream
}

type soundServiceGetSoundJustHelloServer struct {
	grpc.ServerStream
}

func (x *soundServiceGetSoundJustHelloServer) Send(m *ChatServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *soundServiceGetSoundJustHelloServer) Recv() (*ChatClientMessage, error) {
	m := new(ChatClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SoundService_GetSound_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SoundServiceServer).GetSound(&soundServiceGetSoundServer{stream})
}

type SoundService_GetSoundServer interface {
	Send(*ChatServerMessage) error
	Recv() (*ChatClientMessage, error)
	grpc.ServerStream
}

type soundServiceGetSoundServer struct {
	grpc.ServerStream
}

func (x *soundServiceGetSoundServer) Send(m *ChatServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *soundServiceGetSoundServer) Recv() (*ChatClientMessage, error) {
	m := new(ChatClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SoundService_ServiceDesc is the grpc.ServiceDesc for SoundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SoundService",
	HandlerType: (*SoundServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSoundJustHello",
			Handler:       _SoundService_GetSoundJustHello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetSound",
			Handler:       _SoundService_GetSound_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sound_data_streaming.proto",
}
