// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: sound_data_streaming.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The message used in the chat.
type ChatServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Rate int64  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *ChatServerMessage) Reset() {
	*x = ChatServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sound_data_streaming_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatServerMessage) ProtoMessage() {}

func (x *ChatServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sound_data_streaming_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatServerMessage.ProtoReflect.Descriptor instead.
func (*ChatServerMessage) Descriptor() ([]byte, []int) {
	return file_sound_data_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *ChatServerMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChatServerMessage) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type ChatClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data        []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Rate        int64  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	ReadyToSend bool   `protobuf:"varint,3,opt,name=ready_to_send,json=readyToSend,proto3" json:"ready_to_send,omitempty"`
}

func (x *ChatClientMessage) Reset() {
	*x = ChatClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sound_data_streaming_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatClientMessage) ProtoMessage() {}

func (x *ChatClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sound_data_streaming_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatClientMessage.ProtoReflect.Descriptor instead.
func (*ChatClientMessage) Descriptor() ([]byte, []int) {
	return file_sound_data_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *ChatClientMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChatClientMessage) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ChatClientMessage) GetReadyToSend() bool {
	if x != nil {
		return x.ReadyToSend
	}
	return false
}

var File_sound_data_streaming_proto protoreflect.FileDescriptor

var file_sound_data_streaming_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65,
	0x22, 0x5f, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a,
	0x0d, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x74, 0x6f, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72, 0x65, 0x61, 0x64, 0x79, 0x54, 0x6f, 0x53, 0x65, 0x6e,
	0x64, 0x32, 0x9f, 0x01, 0x0a, 0x0c, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x4a, 0x75,
	0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x42, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sound_data_streaming_proto_rawDescOnce sync.Once
	file_sound_data_streaming_proto_rawDescData = file_sound_data_streaming_proto_rawDesc
)

func file_sound_data_streaming_proto_rawDescGZIP() []byte {
	file_sound_data_streaming_proto_rawDescOnce.Do(func() {
		file_sound_data_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(file_sound_data_streaming_proto_rawDescData)
	})
	return file_sound_data_streaming_proto_rawDescData
}

var file_sound_data_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sound_data_streaming_proto_goTypes = []interface{}{
	(*ChatServerMessage)(nil), // 0: proto.ChatServerMessage
	(*ChatClientMessage)(nil), // 1: proto.ChatClientMessage
}
var file_sound_data_streaming_proto_depIdxs = []int32{
	1, // 0: proto.SoundService.GetSoundJustHello:input_type -> proto.ChatClientMessage
	1, // 1: proto.SoundService.GetSound:input_type -> proto.ChatClientMessage
	0, // 2: proto.SoundService.GetSoundJustHello:output_type -> proto.ChatServerMessage
	0, // 3: proto.SoundService.GetSound:output_type -> proto.ChatServerMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sound_data_streaming_proto_init() }
func file_sound_data_streaming_proto_init() {
	if File_sound_data_streaming_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sound_data_streaming_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sound_data_streaming_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sound_data_streaming_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sound_data_streaming_proto_goTypes,
		DependencyIndexes: file_sound_data_streaming_proto_depIdxs,
		MessageInfos:      file_sound_data_streaming_proto_msgTypes,
	}.Build()
	File_sound_data_streaming_proto = out.File
	file_sound_data_streaming_proto_rawDesc = nil
	file_sound_data_streaming_proto_goTypes = nil
	file_sound_data_streaming_proto_depIdxs = nil
}
